backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Media files will be stored in the repo under public/uploads
public_folder: "/uploads" # Folder path where uploaded files will be accessed, relative to the base of the built site

collections:
  - name: "projects" # Used in routes, e.g., /admin/collections/test-collection
    label: "Projects" # Used in the UI
    folder: "src/cms/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter. 
    # Remove any that aren't needed for posts
      - {label: "Project Title", name: "title", widget: "string"}
      - {label: "Repo Links", name: "repo-links", widget: "list", 
        fields: 
          - {label: Repo Name, name: repo-name, widget: string},
          - {label: Repo Url, name: repo-url, widget: string}
          }
      - {label: "List Order", name: "order", widget: "number"}
      - {label: "Tech", name: "tech", widget: "list", field: {label: Tech Name, name: tech-name, widget: string}}
      - {label: "Desktop Screenshots", name: "desktop-screenshots", widget: "list", field: {label: Screenshot, name: desktop-image, widget: image}}
      - {label: "Mobile Screenshots", name: "mobile-screenshots", widget: "list", field: {label: Screenshot, name: mobile-image, widget: image}}
      - {label: "Brief", name: "brief", widget: "string"}
      - {label: "Full Description", name: "full-description", widget: "markdown"}

